# Generated by Django 5.0.1 on 2026-04-04 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimateTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("rainfall", models.FloatField(help_text="Measured rainfall in mm")),
                ("threshold", models.FloatField(help_text="Drought threshold in mm")),
                ("drought", models.BooleanField(default=False)),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=30)),
                ("national_id", models.CharField(max_length=50, unique=True)),
                ("bank_id", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
                ("qualification_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LoanFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "total_capital",
                    models.FloatField(help_text="Total fund capital in USD"),
                ),
                (
                    "available_capital",
                    models.FloatField(help_text="Remaining available capital in USD"),
                ),
                (
                    "funding_source",
                    models.CharField(help_text="e.g. WFP, Government", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.FloatField(help_text="Loan amount in USD")),
                ("term_months", models.IntegerField(default=12)),
                ("grace_period_months", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="MFI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "MFI",
                "verbose_name_plural": "MFIs",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(help_text="Disbursed loan amount in USD")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("available", "Available"),
                            ("disbursed", "Disbursed"),
                            ("repaid", "Repaid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("triggered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="loans.farmer",
                    ),
                ),
                (
                    "loan_fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loans.loanfund",
                    ),
                ),
                (
                    "loan_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loans.loanproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="mfi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loans.mfi",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="mfi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loans.mfi",
            ),
        ),
    ]
