# Generated by Django 5.0.1 on 2026-04-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanfund",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="loanfund",
            name="available_capital",
            field=models.IntegerField(
                default=100000, help_text="Remaining available capital in USD"
            ),
        ),
        migrations.AlterField(
            model_name="loanfund",
            name="total_capital",
            field=models.IntegerField(
                default=100000, help_text="Total fund capital in USD"
            ),
        ),
    ]
