# Generated by Django 5.0.1 on 2026-04-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_loanfund_integer_and_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanfund",
            name="loans_issued",
            field=models.IntegerField(
                default=0, help_text="Number of loans disbursed from this fund"
            ),
        ),
    ]
