# Generated by Django 5.0.1 on 2026-04-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loanfund_add_loans_issued"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(help_text="Requested loan amount in USD"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("tx_hash", models.CharField(blank=True, max_length=100, null=True)),
                ("available_capital_after", models.IntegerField(blank=True, null=True)),
                ("loans_issued_after", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
