# Generated by Django 5.0.1 on 2026-04-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_simulation_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanproduct",
            name="amount",
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_amount",
            field=models.IntegerField(
                default=120, help_text="Maximum loan amount in USD"
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="min_amount",
            field=models.IntegerField(
                default=55, help_text="Minimum loan amount in USD"
            ),
        ),
    ]
